questions =  [
    {"id": 0, "question": "Whytes deserve the BBC.", "effects": {"based": 1}},
    {"id": 1, "question": "Self immolation is an acceptable fetish.", "effects": {"based": 1}},
    {"id": 2, "question": "Killing for fun isn't immoral.", "effects": {"based": 1}},
    {"id": 3, "question": "Being kinky is a good thing.", "effects": {"based": 1}},
    {"id": 4, "question": "\"Exploitation\" is an SJW term to stunt the sex industry.", "effects": {"based": 1}},
    {"id": 5, "question": "It's unlikely that people enjoyed sex back in the older days as it was too vanilla.", "effects": {"based": 1}},
    {"id": 6, "question": "Society should embrace raceplay even if it ends up causing unintended side-effects.", "effects": {"based": 1}},
    {"id": 7, "question": "Trying new things is important even if a lot of new things are bad.", "effects": {"based": 1}},
    {"id": 8, "question": "Porn is bad due to widespread abuse in the industry.", "effects": {"based": -1}},
    {"id": 9, "question": "Porn is bad because it's bad for your mental health.", "effects": {"based": -1}},
    {"id": 10, "question": "It's okay for someone to pay 20 bucks for a Discord profile picture.", "effects": {"based": -1}},
    {"id": 11, "question": "Some things are taboo and that's okay.", "effects": {"based": -1}},
    {"id": 12, "question": "Repetition isn't inherently bad, it's okay to make routine out of things.", "effects": {"based": -1}},
    {"id": 13, "question": "Exploration can be good but sticking to what you like is better.", "effects": {"based": -1}},
    {"id": 14, "question": "Vanilla sex is always better than whatever shit young people come up with.", "effects": {"based": -1}},
    {"id": 15, "question": "Joy of shitting is underrated. Especially if the turd logs are huge.", "effects": {"bottom": 1}},
    {"id": 16, "question": "🥺 is an acceptable emoji to use in the right circumstances.", "effects": {"bottom": 1}},
    {"id": 17, "question": "Listening to authority can be a good thing.", "effects": {"bottom": 1}},
    {"id": 18, "question": "I appreciate and desire emotional support from people close to me.", "effects": {"bottom": 1}},
    {"id": 19, "question": "I get flustered easily.", "effects": {"bottom": 1}},
    {"id": 20, "question": "I [would] do butt stuff.", "effects": {"bottom": 1}},
    {"id": 21, "question": "Enemas are important for your health, especially the health of your gut microfauna.", "effects": {"bottom": 1}},
    {"id": 22, "question": "It's okay to move in with someone even if it means they become the sole breadwinner of the house.", "effects": {"bottom": 1}},
    {"id": 23, "question": "I would rather be by myself than to appease other people.", "effects": {"bottom": -1}},
    {"id": 24, "question": "It feels uncomfortable to depend on someone else, even if they're more than okay with the arrangement.", "effects": {"bottom": -1}},
    {"id": 25, "question": "On their own, emasculation is worse than humiliation.", "effects": {"bottom": -1}},
    {"id": 26, "question": "One's innate sense of self is more important than any emotional help they get from others.", "effects": {"bottom": -1}},
    {"id": 27, "question": "It feels good to have people around you who look up to you and appreciate what you do for them.", "effects": {"bottom": -1}},
    {"id": 28, "question": "I'm a man and I would hate to get my prostate juices squeezed out of my body. Alternatively, I'm a woman and I hate big grithy cocks when they reorganise my insides.", "effects": {"bottom": -1}},
    {"id": 29, "question": "The feeling of being self-dependent is better than the feeling of finding a great partner.", "effects": {"bottom": -1}},
//    {"id": 30, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
//    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
//    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
//    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
//    {"id": 34, "question": "Animals deserve certain universal baseds.", "effects": {"prog": 1}},
//    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
//    {"id": 36, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
//    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
//    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
//    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
//    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
//    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
//    {"id": 42, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}},
//    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
//    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
//    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}}
];
